# Taps

tap "nubjs/tap"

# Shells and terminal

brew "fish"
brew "starship"
brew "tirith"
brew "tmux"
brew "zoxide"
brew "zsh"

# File navigation and text processing

brew "bat"
brew "diffutils"
brew "fd"
brew "fzf"
brew "jq"
brew "lsd"
brew "ripgrep"
# brew "yazi"

# System and network utilities

brew "bind"
brew "btop"
brew "curl"
brew "fastfetch"
brew "stow"
brew "unzip"
brew "wget"

# Docker & Containers

brew "container"

# Editors

brew "neovim"

# Media

brew "ffmpeg"

# Git, Security and credentials

brew "gh"
brew "git"
brew "gitleaks"
brew "gnupg"
brew "lazygit"
brew "pass"

# Languages, runtimes, and package managers

cargo "cargo-binstall"
brew "node"
brew "nubjs/tap/nub", trusted: true
brew "python@3.14"
brew "rust"
brew "rustup"
brew "typescript"
brew "uv"

# Linters, formatters, and parsers

brew "actionlint"
brew "ast-grep"
brew "oxfmt"
brew "oxlint"
brew "shellcheck"
cargo "stylua"
cargo "tree-sitter-cli"

# AI coding tools

brew "rtk"
cargo "zerostack"
npm "@earendil-works/pi-coding-agent"
# npm "@openai/codex"

# Desktop utilities

cask "crisp"

# Fonts

# cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-lxgw-wenkai"
cask "font-maple-mono-nf-cn"
cask "font-smiley-sans"

# Communication and gaming

cask "forkgram"
cask "steamcmd"
