alias cat "bat --paging=never --style=plain"
alias c "clear"
alias e "exit"
alias ff "fastfetch"
alias g "lazygit"
alias ls "lsd"
alias la "lsd -lAh"
alias ll "lsd -lh"
alias lt "lsd --tree"
alias l "lsd -F"
alias t "tmux"
alias ta "tmux attach"
alias v "vim"
alias rmf "rm -rf"
alias rmr "rm -r"
alias z "zerostack"

alias cdc "cd $HOME/.config"
alias cdf "cd $HOME/.config/fish"
alias cdv "cd $HOME/.config/nvim"
alias cdd "cd $HOME/.config/dotfiles"
