status is-interactive; or return

alias cat "bat --paging=never --style=plain"
alias c "clear"
alias e "exit"
alias ff "fastfetch"
alias g "lazygit"
alias ls "lsd"
alias la "lsd -lAh --git"
alias ll "lsd -lh --git"
alias tree "lsd --tree"
alias l "lsd -F"
alias grep "rg --color=auto"
alias diff "diff --color=auto"
alias df "df -h"
alias rmf "rm -rf"
alias rmr "rm -r"
alias t "tmux"
alias ta "tmux attach"
alias v "vim"

alias cdc "cd $HOME/.config"
alias cdd "cd $HOME/.config/dotfiles"
alias cdf "cd $HOME/.config/fish"
alias cdv "cd $HOME/.config/nvim"
alias cdn "cd $HOME/.config/nix"
alias cdp "cd $HOME/.pi/agent"

alias z "zerostack"
